// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ErrorMessagesController from "./error_messages_controller"
application.register("error-messages", ErrorMessagesController)

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HowToUseController from "./how_to_use_controller"
application.register("how-to-use", HowToUseController)

import LoadingCloseController from "./loading_close_controller"
application.register("loading-close", LoadingCloseController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ShowModalController from "./show_modal_controller"
application.register("show-modal", ShowModalController)

import ConfirmDeleteController from "./confirm_delete_controller"
application.register("confirm-delete", ConfirmDeleteController)
